-- ============================================================================
-- FILE    : supabase/demo_data.sql   (generated by scripts/gen-seed.ts — do not hand edit)
-- PROJECT : Handled — AI-run home & business services
-- CREATED : 2026-10-06_0641 UTC
-- PURPOSE : DEMO pros, jobs, applications and a B2B lead for a STAGING project.
--           ⚠ NEVER run on the live database — these are fake people and fake jobs.
-- ============================================================================

insert into public.contractors (business_name, contact_name, email, phone, trades, service_zips, status, rating, jobs_completed, acceptance_rate, on_time_rate, insured_until, background_checked, daily_capacity, coverage, license_number) values
  ('Sparkle Squad Cleaning', 'Dana Reyes', 'dana@sparklesquad.example', '(313) 555-0110', array['cleaning','windows','carpet']::text[], array['48201','48202','48226','482*']::text[], 'approved', 4.9, 212, 0.80, 0.900, current_date + 200, true, 4, '{"auto":"2099-12-31","bond":"2099-12-31","workers_comp":"2099-12-31","passenger_auto":"2099-12-31"}', null),
  ('GreenLine Lawn & Tree', 'Marcus Bell', 'marcus@greenline.example', '(313) 555-0111', array['lawn','tree','gutters']::text[], array['48201','48202','48226','482*']::text[], 'approved', 4.8, 156, 0.83, 0.915, current_date + 200, true, 5, '{"auto":"2099-12-31","bond":"2099-12-31","workers_comp":"2099-12-31","passenger_auto":"2099-12-31"}', null),
  ('Haul Pros Detroit', 'Tony Brooks', 'tony@haulpros.example', '(313) 555-0112', array['hauling','dumpster']::text[], array['48201','48202','48226','482*']::text[], 'approved', 4.7, 98, 0.86, 0.930, current_date + 200, true, 4, '{"auto":"2099-12-31","bond":"2099-12-31","workers_comp":"2099-12-31","passenger_auto":"2099-12-31"}', null),
  ('Fix-It Fred', 'Fred Okafor', 'fred@fixitfred.example', '(313) 555-0113', array['handyman']::text[], array['48201','48202','48226','482*']::text[], 'approved', 4.95, 340, 0.89, 0.945, current_date + 200, true, 3, '{"auto":"2099-12-31","bond":"2099-12-31","workers_comp":"2099-12-31","passenger_auto":"2099-12-31"}', null),
  ('Scoop Troop', 'Lena Park', 'lena@scooptroop.example', '(313) 555-0114', array['pet_waste','lawn']::text[], array['48201','48202','48226','482*']::text[], 'approved', 4.85, 410, 0.92, 0.960, current_date + 200, true, 12, '{"auto":"2099-12-31","bond":"2099-12-31","workers_comp":"2099-12-31","passenger_auto":"2099-12-31"}', null),
  ('Midwest Remodel Co.', 'Sam Patel', 'sam@midwestremodel.example', '(313) 555-0115', array['remodel','handyman']::text[], array['48201','48202','48226','482*']::text[], 'approved', 4.8, 64, 0.95, 0.975, current_date + 200, true, 1, '{"auto":"2099-12-31","bond":"2099-12-31","workers_comp":"2099-12-31","passenger_auto":"2099-12-31"}', 'MI-DEMO-105'),
  ('Fresh Coat Painting', 'Rosa Diaz', 'rosa@freshcoat.example', '(313) 555-0116', array['painting']::text[], array['48201','48202','48226','482*']::text[], 'approved', 4.9, 88, 0.98, 0.990, current_date + 200, true, 2, '{"auto":"2099-12-31","bond":"2099-12-31","workers_comp":"2099-12-31","passenger_auto":"2099-12-31"}', 'MI-DEMO-106'),
  ('Motor City Black Car', 'Andre Wells', 'andre@motorcityblackcar.example', '(313) 555-0117', array['transportation']::text[], array['48201','48202','48226','482*']::text[], 'approved', 4.9, 212, 1.01, 1.005, current_date + 200, true, 6, '{"auto":"2099-12-31","bond":"2099-12-31","workers_comp":"2099-12-31","passenger_auto":"2099-12-31"}', 'MI-DEMO-107')
on conflict (email) do nothing;

insert into public.jobs (service_slug, contact_name, contact_email, contact_phone, customer_type, company_name, address, city, state, zip, answers, frequency, scheduled_date, time_window, estimate_low, estimate_high, status, source) values
  ('house-cleaning', 'Alicia Grant', 'alicia.grant@example.com', '(313) 555-0210', 'residential', null, '100 Woodward Ave', 'Detroit', 'MI', '48201', '{"bedrooms":3,"bathrooms":2,"sqft":1800,"level":"standard","pets":false,"fridge_oven":false}'::jsonb, 'biweekly', current_date + 1, 'morning', 159, 189, 'requested', 'web'),
  ('junk-removal', 'Brightside Dental', 'brightside.dental@example.com', '(313) 555-0211', 'commercial', 'Brightside Dental', '137 Woodward Ave', 'Detroit', 'MI', '48226', '{"volume":"quarter","kind":"household","special":0,"stairs":false}'::jsonb, 'once', current_date + 2, 'morning', 234, 304, 'scheduled', 'web'),
  ('tree-removal', 'Kevin Moore', 'kevin.moore@example.com', '(313) 555-0212', 'residential', null, '174 Woodward Ave', 'Detroit', 'MI', '48202', '{"work":"remove","height":"medium","trees":1,"near_structure":false,"stump":false}'::jsonb, 'once', current_date + 3, 'morning', 724, 1219, 'site_visit', 'web'),
  ('pet-waste-removal', 'Priya Shah', 'priya.shah@example.com', '(313) 555-0213', 'residential', null, '211 Woodward Ave', 'Detroit', 'MI', '48201', '{"dogs":1,"yard":"medium","first_cleanup":false,"deodorize":false}'::jsonb, 'weekly', current_date + 4, 'morning', 24, 29, 'assigned', 'web'),
  ('bathroom-remodel', 'Jordan Lee', 'jordan.lee@example.com', '(313) 555-0214', 'residential', null, '248 Woodward Ave', 'Detroit', 'MI', '48202', '{"scope":"mid","sqft":60,"count":1}'::jsonb, 'once', current_date + 5, 'morning', 17254, 28254, 'quoted', 'web'),
  ('gutter-cleaning', 'Hector Diaz', 'hector.diaz@example.com', '(313) 555-0215', 'residential', null, '285 Woodward Ave', 'Detroit', 'MI', '48226', '{"feet":150,"stories":"1","guards":false}'::jsonb, 'once', current_date + 6, 'morning', 179, 219, 'completed', 'web');

-- assign the demo 'assigned' + 'completed' jobs to a matching pro
update public.jobs j set contractor_id = c.id, contractor_payout = floor(j.estimate_low * s.payout_share)
from public.contractors c, public.services s
where s.slug = j.service_slug and j.status in ('assigned','completed') and j.service_slug = 'pet-waste-removal' and c.email = 'lena@scooptroop.example';
update public.jobs j set contractor_id = c.id, contractor_payout = floor(j.estimate_low * s.payout_share), price_final = j.estimate_low, completed_at = now()
from public.contractors c, public.services s
where s.slug = j.service_slug and j.status = 'completed' and c.email = 'marcus@greenline.example';

-- every non-site-visit job has a firm price; every job past booking has been paid (upfront)
update public.jobs set price_final = estimate_low where price_final is null and status not in ('site_visit','quoted');
update public.jobs set price_final = coalesce(price_final, estimate_low), paid_at = now(), amount_paid = coalesce(price_final, estimate_low)
where status in ('scheduled','dispatched','assigned','in_progress','qa_review','completed');
update public.jobs j set contractor_payout = floor(j.price_final * s.payout_share) from public.services s
where s.slug = j.service_slug and j.paid_at is not null and j.contractor_payout is null;

insert into public.contractor_applications (business_name, contact_name, email, phone, trades, zips, years_experience, crew_size, insured, message) values
  ('Clear View Windows', 'Ray Thompson', 'ray@clearview.example', '(313) 555-0301', array['windows','gutters'], '48201, 48202', 6, 2, true, 'Two-man crew, own lifts, 6 years in business.');

insert into public.business_accounts (company, contact_name, email, locations, services_needed, status, monthly_value) values
  ('Brightside Dental', 'Office Manager', 'office@brightside.example', 3, array['house-cleaning','window-cleaning'], 'proposal', 2400);

