-- ============================================================================
-- FILE    : supabase/seed.sql   (generated by scripts/gen-seed.ts — do not hand edit)
-- PROJECT : Handled — AI-run home & business services
-- CREATED : 2026-10-01_2042 UTC
-- PURPOSE : PRODUCTION seed — service catalog + launch market. Safe to re-run.
-- ============================================================================

insert into public.services (slug, name, category, minimum, payout_share, site_visit, sort) values
  ('house-cleaning', 'House & Office Cleaning', 'cleaning', 120, 0.65, false, 0),
  ('window-cleaning', 'Window Cleaning', 'cleaning', 149, 0.65, false, 1),
  ('carpet-cleaning', 'Carpet & Upholstery Cleaning', 'cleaning', 129, 0.65, false, 2),
  ('organizing', 'Organizing & Decluttering', 'cleaning', 199, 0.65, false, 3),
  ('gutter-cleaning', 'Gutter Cleaning', 'cleaning', 149, 0.65, false, 4),
  ('lawn-care', 'Lawn Care', 'outdoor', 45, 0.7, false, 5),
  ('tree-removal', 'Tree Removal & Trimming', 'outdoor', 250, 0.75, true, 6),
  ('leaf-removal', 'Leaf Removal', 'outdoor', 125, 0.7, false, 7),
  ('snow-removal', 'Snow Removal', 'outdoor', 45, 0.7, false, 8),
  ('pet-waste-removal', 'Dog Poop Removal', 'outdoor', 20, 0.7, false, 9),
  ('junk-removal', 'Junk Removal', 'removal', 129, 0.65, false, 10),
  ('large-item-removal', 'Large Item Removal', 'removal', 99, 0.65, false, 11),
  ('handyman', 'Handyman', 'repair_remodel', 99, 0.7, false, 12),
  ('plumbing', 'Plumbing Repairs', 'repair_remodel', 149, 0.7, false, 13),
  ('water-heater', 'Water Heater Replacement', 'repair_remodel', 1400, 0.75, false, 14),
  ('hvac-install', 'HVAC Installation', 'repair_remodel', 3500, 0.8, true, 15),
  ('lighting-install', 'Lighting & Ceiling Fan Install', 'repair_remodel', 149, 0.7, false, 16),
  ('camera-install', 'Security Camera Install', 'repair_remodel', 149, 0.7, false, 17),
  ('garbage-disposal', 'Garbage Disposal Repair & Replace', 'repair_remodel', 149, 0.7, false, 18),
  ('bathroom-remodel', 'Bathroom Remodel', 'repair_remodel', 3500, 0.85, true, 19),
  ('kitchen-remodel', 'Kitchen Remodel', 'repair_remodel', 12000, 0.85, true, 20),
  ('home-remodel', 'Whole-Home Remodel', 'repair_remodel', 25000, 0.85, true, 21),
  ('event-package', 'Plan My Event (by Budget)', 'events', 1000, 0.82, true, 22),
  ('event-planning', 'Event Planning & Coordination', 'events', 650, 0.75, true, 23),
  ('catering', 'Catering', 'events', 600, 0.8, false, 24),
  ('food-truck', 'Food Truck Booking', 'events', 1200, 0.8, false, 25),
  ('dj-music', 'DJ & Live Music', 'events', 450, 0.8, false, 26),
  ('event-rentals', 'Seating & Party Rentals', 'events', 250, 0.75, false, 27),
  ('event-venue', 'Event Space Rental & Coordination', 'events', 800, 0.85, true, 28)
on conflict (slug) do update set name = excluded.name, category = excluded.category, minimum = excluded.minimum,
  payout_share = excluded.payout_share, site_visit = excluded.site_visit, sort = excluded.sort;

insert into public.markets (name, state, zip_prefixes)
select 'Metro Detroit', 'MI', array['480','481','482','483'] where not exists (select 1 from public.markets where name = 'Metro Detroit');

