/*
 * FILE    : apps/mobile/lib/es-app.ts
 * PROJECT : Handled (myhumanai) — AI-run home & business services
 * CREATED : 2026-10-02_1405 UTC
 * UPDATED : 2026-10-03_0152 UTC — market pricing (raise your offer / pros' counters on the job screen).
 * PURPOSE : Spanish for the customer screens of the app (home, booking, my bookings, job,
 *           account, sign-in, chat). Shared words live in @handled/core i18n.ts.
 */
export const ES_APP: Record<string, string> = {
  "What can we take off your plate?": "¿Qué pendiente le quitamos de encima?",
  "BRAND_PITCH": "Una sola app para todo lo que su hogar o negocio necesita: limpieza, reparaciones, pintura, retiro de cosas, jardín y nieve, mascotas, lavado de autos, víveres y entregas médicas, eventos y transporte. Precios por adelantado, profesionales verificados y un equipo con IA que se asegura de que quede bien.",
  "Ask for a price": "Pida un precio",
  "My bookings": "Mis reservas",
  "Open Pro mode": "Abrir modo profesional",
  "Become a pro — get prepaid jobs": "Sea profesional — trabajos prepagados",
  "Signed in as": "Sesión iniciada como",
  "Account & sign out": "Cuenta y cerrar sesión",
  "No jobs yet. Bookings made with your email appear here.": "Aún no hay trabajos. Las reservas hechas con su correo aparecen aquí.",
  "date TBD": "fecha por definir",
  "Date TBD": "Fecha por definir",
  "Couldn't add photos": "No se pudieron agregar las fotos",
  "Photos added": "Fotos agregadas",
  "Your pro can see them now.": "Su profesional ya puede verlas.",
  "Payment": "Pago",
  "Couldn't start payment": "No se pudo iniciar el pago",
  "Couldn't save": "No se pudo guardar",
  "Thank you!": "¡Gracias!",
  "Your rating helps us send the best pros.": "Su calificación nos ayuda a enviar a los mejores profesionales.",
  "Covered ✓": "Asignado ✓",
  "jobs completed · vetted & insured": "trabajos completados · verificado y asegurado",
  "Finding your pro…": "Buscando a su profesional…",
  "You'll get a notification the moment your job is covered.": "Le avisaremos en cuanto su trabajo tenga profesional asignado.",
  "Price": "Precio",
  "No charge": "Sin costo",
  "Paid": "Pagado",
  "Payment due — your pro is dispatched once paid": "Pago pendiente — enviamos a su profesional al recibir el pago",
  "Firm price after the free site visit": "Precio final después de la visita gratuita",
  "Pay": "Pagar",
  "Invoice & service agreement": "Factura y acuerdo de servicio",
  "Add photos for your pro": "Agregue fotos para su profesional",
  "More angles, a close-up, the spot you're worried about.": "Más ángulos, un acercamiento, el lugar que le preocupa.",
  "on file.": "guardadas.",
  "Tip your pro": "Dé propina a su profesional",
  "100% goes to your pro.": "El 100% es para su profesional.",
  "Couldn't tip": "No se pudo enviar la propina",
  "Submit rating": "Enviar calificación",
  "Timeline": "Historial",
  "Your pro": "Su profesional",
  "Your pro has arrived": "Su profesional llegó",
  "Reschedule": "Cambiar fecha",
  "Pick a new day and time": "Elija un nuevo día y horario",
  "Free until 24 hours before. If your pro isn't free at the new time, we'll match another vetted pro.": "Gratis hasta 24 horas antes. Si su profesional no está libre en el nuevo horario, le asignamos otro profesional verificado.",
  "Moving…": "Cambiando…",
  "Move my booking": "Cambiar mi reserva",
  "Couldn't move it": "No se pudo cambiar",
  "Moved ✓": "Cambiada ✓",
  "Same pro, new time.": "Mismo profesional, nuevo horario.",
  "We're matching a pro for the new time.": "Estamos asignando un profesional para el nuevo horario.",
  "Keep current time": "Mantener horario actual",
  "Photos needed": "Se necesitan fotos",
  "Free site visit": "Visita gratuita al sitio",
  "Nothing is charged until you approve the firm quote.": "No se cobra nada hasta que apruebe la cotización final.",
  "Book free visit": "Reservar visita gratuita",
  "Checked from your photos": "Revisado con sus fotos",
  "Edit details": "Editar detalles",
  "Continue at": "Continuar por",
  "Couldn't book": "No se pudo reservar",
  "Please check the form": "Revise el formulario",
  "Booked": "Reservado",
  "A pro will visit to confirm your firm price.": "Un profesional lo visitará para confirmar su precio final.",
  "A coordinator will contact you to take payment — your pro is confirmed once it's paid.": "Un coordinador le contactará para el pago — su profesional se confirma al recibirlo.",
  "Free site visit confirms the firm price.": "La visita gratuita confirma el precio final.",
  "Your budget (optional, $)": "Su presupuesto (opcional, $)",
  "What you'd like to spend": "Lo que le gustaría gastar",
  "Notes for the pro": "Notas para el profesional",
  "Gate code, pets, what needs hauling…": "Código del portón, mascotas, qué hay que llevarse…",
  "Our AI checks your photos so the price fits the job — no surprises on the day.": "Nuestra IA revisa sus fotos para que el precio corresponda al trabajo — sin sorpresas ese día.",
  "Promo, gift card or referral code (optional)": "Código promocional, de regalo o de referido (opcional)",
  "Savings and Plus member pricing are applied at checkout.": "Los ahorros y precios de miembro Plus se aplican al pagar.",
  "Contact": "Contacto",
  "How would you like to pay?": "¿Cómo desea pagar?",
  "Pay in full": "Pagar completo",
  "Deposit": "Depósito",
  "I agree": "Acepto",
  "to the": "el",
  "Service Agreement": "Acuerdo de servicio",
  ": pay upfront, free redo or refund if it's not right.": ": pago por adelantado, se rehace gratis o se reembolsa si no queda bien.",
  "Choose when you need it done": "Elija para cuándo lo necesita",
  "Checking your price…": "Revisando su precio…",
  "Book free site visit": "Reservar visita gratuita",
  "Delete your account?": "¿Eliminar su cuenta?",
  "This removes your login, profile, phone, devices and photos, and cancels any membership. Invoices and payment records (name and email only) are kept for tax law. This can't be undone.": "Esto elimina su acceso, perfil, teléfono, dispositivos y fotos, y cancela cualquier membresía. Las facturas y registros de pago (solo nombre y correo) se conservan por ley fiscal. No se puede deshacer.",
  "Keep my account": "Conservar mi cuenta",
  "Delete permanently": "Eliminar definitivamente",
  "Couldn't delete yet": "Aún no se puede eliminar",
  "Please contact support.": "Comuníquese con soporte.",
  "Account deleted": "Cuenta eliminada",
  "Your account and personal details have been deleted.": "Su cuenta y sus datos personales fueron eliminados.",
  "Account": "Cuenta",
  "Language": "Idioma",
  "you're a member": "usted es miembro",
  "month": "mes",
  "Manage or cancel": "Administrar o cancelar",
  "Join Plus": "Unirse a Plus",
  "Share my code": "Compartir mi código",
  "Sign out": "Cerrar sesión",
  "Deleting…": "Eliminando…",
  "Delete my account": "Eliminar mi cuenta",
  "Customers and pros — we'll email you a code.": "Clientes y profesionales — le enviaremos un código por correo.",
  "Send code": "Enviar código",
  "6-digit code": "Código de 6 dígitos",
  "Verify": "Verificar",
  "By continuing you agree to our": "Al continuar acepta nuestro",
  "and": "y",
  "Privacy Policy": "Política de privacidad",
  "Hi! Tell me the job and I'll give you a price.": "¡Hola! Cuénteme el trabajo y le doy un precio.",
  "Sorry, something went wrong.": "Lo sentimos, algo salió mal.",
  "e.g. haul away an old couch": "p. ej. llevarse un sofá viejo",
  "Send": "Enviar",
  "Book": "Reservar",
  "Concierge": "Asistente",
  "Booking": "Reserva",
  "Pro": "Profesional",
  "Job offer": "Oferta de trabajo",
  "Enter your ZIP to see open dates.": "Ingrese su código postal para ver fechas disponibles.",
  "We're adding pros in your area — pick a time and we'll confirm within one business day.": "Estamos sumando profesionales en su zona — elija un horario y le confirmamos en un día hábil.",
  "closed": "cerrado",
  "full": "lleno",
  "few left": "quedan pocos",
  "left": "disponibles",
  "Loading…": "Cargando…",
  "Try again": "Intente de nuevo",
  "Cancel": "Cancelar",
  "Pickup time (e.g. 5:30 am)": "Hora de recogida (p. ej. 5:30 a. m.)",
  "Start time (e.g. 6:00 pm)": "Hora de inicio (p. ej. 6:00 p. m.)",
  "Photos — recommended": "Fotos — recomendadas",
  "Photos (optional)": "Fotos (opcional)",
  "Estimated range": "Rango estimado",
  "Your price": "Su precio",
  "Per visit": "Por visita",
  "Details": "Detalles",

  // Market pricing — raise your offer (job screen)
  "Couldn't raise your offer": "No se pudo subir su oferta",
  "Offer raised ✓": "Oferta subida ✓",
  "Pros who'd do it for a bit more can send a counter offer — see and accept them on your booking page on the website.": "Los profesionales que lo harían por un poco más pueden enviar una contraoferta — véalas y acéptelas en la página de su reserva en el sitio web.",
  "See pros' counter offers": "Ver contraofertas de profesionales",
};
