/*
 * FILE    : apps/mobile/lib/es-pro.ts
 * PROJECT : Handled (HandledServices) — AI-run home & business services
 * CREATED : 2026-10-02_1405 UTC
 * UPDATED : 2026-10-02_1405 UTC — English / Spanish.
 * UPDATED : 2026-10-03_1337 UTC — My crew, fast track to Pro+, and hand-back-a-job strings.
 * UPDATED : 2026-10-04_2204 UTC — Jobs near you (open job board) and customer requests.
 * UPDATED : 2026-10-05_0418 UTC — Rewards.
 * UPDATED : 2026-10-06_1950 UTC — standby requests and the cancel tiers.
 * UPDATED : 2026-10-06_2120 UTC — your cancellations card.
 * PURPOSE : Spanish for the pro screens of the app (offers, jobs, calendar, earnings).
 */
export const ES_PRO: Record<string, string> = {
  // Time windows
  "Morning (8–11am)": "Mañana (8–11 a. m.)",
  "Midday (11am–2pm)": "Mediodía (11 a. m.–2 p. m.)",
  "Afternoon (2–5pm)": "Tarde (2–5 p. m.)",
  "Any time that day": "Cualquier hora ese día",

  // Common
  "Couldn't update": "No se pudo actualizar",
  "Try again": "Inténtelo de nuevo",
  "Cancel": "Cancelar",
  "Loading…": "Cargando…",
  "Never mind": "No importa",
  "Yes": "Sí",
  "No": "No",

  // Pro home
  "Setup & documents": "Configuración y documentos",
  "Earnings": "Ganancias",
  "You're on call": "Está de guardia",
  "Off call": "Fuera de guardia",
  "Same-day jobs near you come to you first": "Los trabajos para el mismo día cerca de usted le llegan primero",
  "until": "hasta las",
  "Go on call to get same-day jobs, even on a day you don't usually work.": "Póngase de guardia para recibir trabajos para el mismo día, incluso en un día que normalmente no trabaja.",
  "Go off call": "Salir de guardia",
  "On call": "De guardia",
  "Sharing your location while on call or on a job today (app open only).": "Compartiendo su ubicación mientras está de guardia o en un trabajo hoy (solo con la app abierta).",
  "Your location isn't shared when you're off call and not on a job.": "Su ubicación no se comparte cuando está fuera de guardia y no está en un trabajo.",
  "My calendar & days off": "Mi calendario y días libres",
  "New offers": "Nuevas ofertas",
  "No open offers. We'll notify you when one comes in.": "No hay ofertas abiertas. Le avisaremos cuando llegue una.",
  "site visit": "visita al sitio",
  "View & accept": "Ver y aceptar",
  "My schedule": "Mi agenda",
  "Nothing scheduled.": "Nada programado.",

  // Earnings
  "Payout setup": "Configuración de pagos",
  "Not available yet": "Aún no disponible",
  "Cash out now?": "¿Cobrar ahora?",
  "Cash out": "Cobrar",
  "Couldn't cash out": "No se pudo cobrar",
  "Ready to pay out": "Listo para pagar",
  "Instant pay": "Pago inmediato",
  "Approved payouts go out free on the weekly run.": "Los pagos aprobados se envían gratis en el pago semanal.",
  "connect your bank or debit card through Stripe once, then cash out any time for": "conecte su banco o tarjeta de débito mediante Stripe una vez y luego cobre cuando quiera por",
  "Set up instant pay": "Configurar pago inmediato",
  "Paid to you this year:": "Pagado a usted este año:",
  "Payouts": "Pagos",
  "No payouts yet this year.": "Aún no hay pagos este año.",
  "instant": "inmediato",
  "fee": "cargo",
  "Full statement & 1099 (web)": "Estado de cuenta completo y 1099 (web)",
  // Payout kinds
  "Job": "Trabajo",
  "Show-up pay": "Pago por presentarse",
  "Weekly minimum": "Mínimo semanal",
  "Insurance stipend": "Subsidio de seguro",
  "Materials": "Materiales",
  "Adjustment": "Ajuste",
  // Payout statuses
  "pending": "pendiente",
  "approved": "aprobado",
  "paid": "pagado",
  "held": "retenido",
  "clawback": "reembolso",
  // Instant pay / reimbursement reasons
  "not offered right now": "no se ofrece en este momento",
  "pro isn't active": "el profesional no está activo",
  "not offered for this trade": "no se ofrece para este oficio",
  "pro not found": "profesional no encontrado",

  // Job sheet
  "Upload failed": "Error al subir",
  "Receipt": "Recibo",
  "Add the amount, what you bought and a photo of the receipt.": "Agregue el monto, lo que compró y una foto del recibo.",
  "Not accepted": "No aceptado",
  "Receipt sent": "Recibo enviado",
  "Sent for approval.": "Enviado para aprobación.",
  "Approved — you're reimbursed once the customer pays.": "Aprobado: se le reembolsa cuando el cliente pague.",
  "Not sent": "No enviado",
  "Change order sent": "Orden de cambio enviada",
  "Can't get in": "No puede entrar",
  "Say what happened (knocked, called, gate locked…).": "Indique qué pasó (tocó, llamó, portón cerrado…).",
  "Couldn't send": "No se pudo enviar",
  "We're on it": "Nos encargamos",
  "We're calling the customer now. Please wait 15 minutes on site. A confirmed lockout earns show-up pay.": "Estamos llamando al cliente ahora. Espere 15 minutos en el lugar. Un acceso denegado confirmado recibe pago por presentarse.",
  "Payout": "Pago",
  "On my way": "En camino",
  "The customer can see your ETA while the app is open.": "El cliente puede ver su hora estimada de llegada mientras la app está abierta.",
  "I've arrived — start job": "Ya llegué: iniciar trabajo",
  "Finish the job": "Terminar el trabajo",
  "Photograph every area you worked on. AI checks them and approves your payout.": "Fotografíe cada área en la que trabajó. La IA las revisa y aprueba su pago.",
  "Take photos": "Tomar fotos",
  "Note for the customer (optional)": "Nota para el cliente (opcional)",
  "Mark complete": "Marcar como terminado",
  "Submitted — AI quality check in progress.": "Enviado: revisión de calidad con IA en curso.",
  "More work than booked?": "¿Más trabajo del reservado?",
  "Update the scope to what's really here": "Actualice el alcance a lo que realmente hay",
  "The difference is priced at our standard rates and sent to the customer to approve and pay.": "La diferencia se cotiza con nuestras tarifas estándar y se envía al cliente para que la apruebe y pague.",
  "What you found (the customer sees this)": "Lo que encontró (el cliente lo verá)",
  "Extra for the customer:": "Cargo adicional para el cliente:",
  "No extra charge for this change": "Sin cargo adicional por este cambio",
  "Send change order": "Enviar orden de cambio",
  "Can't get in?": "¿No puede entrar?",
  "Can't get access": "No puede acceder",
  "Knocked and called at 9:05, gate locked, no answer…": "Toqué y llamé a las 9:05, portón cerrado, nadie respondió…",
  "Report no access": "Reportar falta de acceso",
  "Purchases": "Compras",
  "Reimbursement:": "Reembolso:",
  "Materials for this job are included in your payout.": "Los materiales de este trabajo están incluidos en su pago.",
  "Store purchases for the customer": "Compras en tienda para el cliente",
  "Parts not included in the price": "Piezas no incluidas en el precio",
  "$ amount": "Monto en $",
  "What you bought (e.g. supplies at Home Depot)": "Lo que compró (p. ej., materiales en Home Depot)",
  "What you bought (e.g. wax ring + supply line)": "Lo que compró (p. ej., anillo de cera + manguera de suministro)",
  "Receipt added ✓ (retake)": "Recibo agregado ✓ (volver a tomar)",
  "Photo of receipt": "Foto del recibo",
  "Submit receipt": "Enviar recibo",
  // Expense statuses
  "waiting for approval": "en espera de aprobación",
  "approved — waiting on the customer": "aprobado: en espera del cliente",
  "reimbursed": "reembolsado",
  "not approved": "no aprobado",

  // Calendar
  "My calendar": "Mi calendario",
  "Change usual days, hours or daily limit": "Cambiar días habituales, horario o límite diario",
  "Today": "Hoy",
  "booked": "reservados",
  "Day off": "Día libre",
  "Doesn't work Sundays": "No trabaja los domingos",
  "Doesn't work Mondays": "No trabaja los lunes",
  "Doesn't work Tuesdays": "No trabaja los martes",
  "Doesn't work Wednesdays": "No trabaja los miércoles",
  "Doesn't work Thursdays": "No trabaja los jueves",
  "Doesn't work Fridays": "No trabaja los viernes",
  "Doesn't work Saturdays": "No trabaja los sábados",
  "Reopen this day": "Reabrir este día",
  "Take this day off": "Tomar este día libre",

  // Offer
  "Offer unavailable": "Oferta no disponible",
  "Loading offer…": "Cargando oferta…",
  "Not available": "No disponible",
  "Another pro may have taken it.": "Es posible que otro profesional la haya tomado.",
  "It's yours": "Es suyo",
  "The full address and customer details are now unlocked.": "La dirección completa y los datos del cliente ya están desbloqueados.",
  "Where": "Dónde",
  "Scope": "Alcance",
  "Start time": "Hora de inicio",
  "Included:": "Incluye:",
  "Customer:": "Cliente:",
  "Instructions:": "Instrucciones:",
  "Job terms": "Condiciones del trabajo",
  "Your payout": "Su pago",
  "Site visit": "Visita al sitio",
  "Expires in": "Vence en",
  "I agree to this work order and its job terms": "Acepto esta orden de trabajo y sus condiciones",
  "Pass": "Pasar",
  "Accept job": "Aceptar trabajo",
  "You accepted this job": "Usted aceptó este trabajo",
  "This offer expired or another pro took it.": "Esta oferta venció u otro profesional la tomó.",
  // Fixed job terms from the work order
  "Arrive within the booked window. Running late? Message the customer in the app before the window starts.": "Llegue dentro del horario reservado. ¿Va con retraso? Envíe un mensaje al cliente en la app antes de que empiece el horario.",
  "Take before-and-after photos of every area you work on and upload them to complete the job.": "Tome fotos de antes y después de cada área en la que trabaje y súbalas para terminar el trabajo.",
  "The customer has paid a deposit; we collect the balance before your start date. Don't start until the app shows \"Paid in full\".": "El cliente pagó un depósito; cobramos el saldo antes de su fecha de inicio. No comience hasta que la app muestre \"Pagado en su totalidad\".",
  "Out-of-scope work: stop and tell us — we send the customer a change order. Do only what's on this work order.": "Trabajo fuera del alcance: deténgase y avísenos; le enviamos al cliente una orden de cambio. Haga solo lo que está en esta orden de trabajo.",
  "Parts not included in the price: upload the receipt in the app. Small amounts are approved automatically; call us before a big purchase. You're reimbursed at cost once the customer pays.": "Piezas no incluidas en el precio: suba el recibo en la app. Los montos pequeños se aprueban automáticamente; llámenos antes de una compra grande. Se le reembolsa al costo cuando el cliente pague.",
  "Can't get in? Tap “Can't get in?” in the app and wait 15 minutes while we call the customer. A confirmed lockout earns show-up pay.": "¿No puede entrar? Toque “¿No puede entrar?” en la app y espere 15 minutos mientras llamamos al cliente. Un acceso denegado confirmado recibe pago por presentarse.",
  "Don't solicit this customer to book directly with you for 12 months.": "No le pida a este cliente que reserve directamente con usted durante 12 meses.",
  "Licensed trade: your license must be valid for this work; pull permits where required.": "Oficio con licencia: su licencia debe ser válida para este trabajo; obtenga los permisos donde se requieran.",
  "Event work: be set up and ready before the start time; coordinate with the on-site planner.": "Trabajo de eventos: esté instalado y listo antes de la hora de inicio; coordine con el organizador en el lugar.",
  // Crew accounts (pro/crew.tsx, job sheet)
  "My crew": "Mi equipo",
  "Have people who work with you? List them here to send them on your company’s jobs. Each person passes the same background check you did before entering a customer’s home. Your crew works for your company: you decide who goes, and your payout covers the whole job.": "¿Tiene gente que trabaja con usted? Regístrela aquí para enviarla a trabajos de su empresa. Cada persona aprueba la misma verificación de antecedentes que usted antes de entrar a la casa de un cliente. Su equipo trabaja para su empresa: usted decide quién va, y su pago cubre todo el trabajo.",
  "Step 1: sign the Crew Addendum": "Paso 1: firme el Anexo de Equipo de Trabajo",
  "Your crew works for your company: you direct and pay them.": "Su equipo trabaja para su empresa: usted los dirige y les paga.",
  "Everyone is legally allowed to work in the U.S.; your company keeps their I-9.": "Cada persona tiene permiso legal para trabajar en los EE. UU.; su empresa guarda su I-9.",
  "Workers’ comp for your crew before any job.": "Seguro de accidentes laborales para su equipo antes de cualquier trabajo.",
  "Everyone listed and background-checked.": "Todos registrados y con verificación de antecedentes aprobada.",
  "Licensed work only to license holders; helpers never go alone.": "Trabajo con licencia solo para quien tiene la licencia; los ayudantes nunca van solos.",
  "Read the Crew Addendum": "Leer el Anexo de Equipo de Trabajo",
  "I agree. Everyone I list is legally allowed to work in the U.S., and my company handles their I-9, payroll and workers’ comp.": "Acepto. Cada persona que registre tiene permiso legal para trabajar en los EE. UU., y mi empresa se encarga de su I-9, nómina y seguro de accidentes laborales.",
  "Your full name (signature)": "Su nombre completo (firma)",
  "Sign": "Firmar",
  "You can add your crew and start their checks now. To send them on jobs:": "Puede agregar a su equipo y empezar sus verificaciones ya. Para enviarlos a trabajos:",
  "upload a current workers’ comp policy (the no-employees statement doesn’t cover a crew)": "suba una póliza vigente de seguro de accidentes laborales (la declaración de que no tiene empleados no cubre a un equipo)",
  "Sign the Crew Addendum first": "Primero firme el Anexo de Equipo de Trabajo",
  "Your crew": "Su equipo",
  "No one yet. Add your first person below.": "Todavía no hay nadie. Agregue a la primera persona abajo.",
  "license": "licencia",
  "yrs": "años",
  "Remove": "Quitar",
  "Remove them from your crew? Do this the day they stop working with you.": "¿Quitar a esta persona de su equipo? Hágalo el día en que deje de trabajar con usted.",
  "Add someone": "Agregar a alguien",
  "We email them a secure link from our screening provider (Checkr) to consent. It usually takes 1–3 business days.": "Le enviamos por correo un enlace seguro de nuestro proveedor de verificación (Checkr) para dar su consentimiento. Normalmente tarda de 1 a 3 días hábiles.",
  "Email (gets the background check link)": "Correo (recibe el enlace de verificación)",
  "Phone": "Teléfono",
  "Their language": "Su idioma",
  "Role": "Función",
  "Trades": "Oficios",
  "Years of experience": "Años de experiencia",
  "Michigan license number": "Número de licencia de Michigan",
  "Add and send background check": "Agregar y enviar verificación de antecedentes",
  "Crew lead": "Jefe de cuadrilla",
  "Licensed tech": "Técnico con licencia",
  "Apprentice": "Aprendiz",
  "Helper": "Ayudante",
  "Runs jobs on their own for your company (unlicensed work).": "Hace trabajos por su cuenta para su empresa (trabajo sin licencia).",
  "Holds their own Michigan trade license (journeyman or master).": "Tiene su propia licencia de oficio de Michigan (oficial o maestro).",
  "Registered apprentice; works with a licensed tech on licensed jobs.": "Aprendiz registrado; trabaja con un técnico con licencia en trabajos con licencia.",
  "Goes along with you or a crew lead; never sent alone.": "Va con usted o con un jefe de cuadrilla; nunca va solo.",
  "Not started": "No iniciada",
  "Link sent: waiting on them": "Enlace enviado: esperando a la persona",
  "In progress": "En proceso",
  "Clear: can go to jobs": "Aprobada: puede ir a trabajos",
  "Under review": "En revisión",
  "On hold": "En pausa",
  "Canceled": "Cancelada",
  "Who’s doing this job?": "¿Quién va a este trabajo?",
  "Me": "Yo mismo",
  "To send your crew:": "Para enviar a su equipo:",
  "The customer sees the first name of who’s coming.": "El cliente ve el nombre de pila de quien va.",
  "Not active": "No está activo",
  "Background check not clear yet": "La verificación de antecedentes aún no está aprobada",
  "Helpers go along with a lead, never alone": "Los ayudantes van con un jefe de cuadrilla, nunca solos",
  "Licensed work needs a licensed tech": "El trabajo con licencia necesita un técnico con licencia",
  "Not licensed for this trade": "No tiene licencia para este oficio",

  // Fast track (pro/fast-track.tsx, home)
  "Fast track": "Vía rápida",
  "Fast track to Pro+": "Vía rápida a Pro+",
  "Already a master at your trade? Start at Pro+ with the fast track →": "¿Ya es maestro en su oficio? Empiece en Pro+ con la vía rápida →",
  "Fast track: we’re reviewing your portfolio": "Vía rápida: estamos revisando su portafolio",
  "Fast track: your next finished job is your trial": "Vía rápida: su próximo trabajo terminado es su prueba",
  "Fast track: see our answer": "Vía rápida: vea la respuesta",
  "Back to jobs": "Volver a trabajos",
  "We have your application. We’re reviewing your portfolio and will let you know by email and in the app.": "Recibimos su solicitud. Estamos revisando su portafolio y le avisaremos por correo y en la aplicación.",
  "Your portfolio passed! The next job you finish is your trial job. Do it like you always do and take good photos at the end.": "¡Su portafolio pasó! El próximo trabajo que termine es su trabajo de prueba. Hágalo como siempre y tome buenas fotos al terminar.",
  "We didn’t approve the fast track this time:": "Esta vez no aprobamos la vía rápida:",
  "You keep getting offers and reach Pro+ the normal way.": "Sigue recibiendo ofertas y llega a Pro+ de la forma normal.",
  "Years in the trade": "Años en el oficio",
  "Your experience": "Su experiencia",
  "Tell us about your experience: the work you do, where you learned, jobs you’re proud of.": "Cuéntenos de su experiencia: qué tipo de trabajos hace, dónde aprendió, trabajos de los que está orgulloso. Puede escribir en español.",
  "References (optional)": "Referencias (opcional)",
  "Customers or contractors, with phone": "Clientes o contratistas, con teléfono",
  "Photos of your work": "Fotos de su trabajo",
  "Before-and-after works best. The work only: no people, documents or addresses.": "Antes y después funciona mejor. Solo el trabajo: sin personas, documentos ni direcciones.",
  "From library": "De la galería",
  "Send application": "Enviar solicitud",
  "A few more words about your experience, please.": "Unas palabras más sobre su experiencia, por favor.",

  // Hand back a job (job sheet)
  "Can't make it? Hand this job back": "¿No puede ir? Devuelva este trabajo",
  "Reason (only we see it)": "Motivo (solo lo vemos nosotros)",
  "Hand it back": "Devolverlo",
  "Jobs near you": "Trabajos cerca de usted",
  "Paid jobs nobody has taken yet that fit your trades, area and schedule. First to take it gets it. Taking them is always up to you.": "Trabajos pagados que nadie ha tomado y que encajan con sus oficios, zona y horario. El primero en tomarlo se lo lleva. Tomarlos es opcional.",
  "No open jobs near you right now.": "No hay trabajos abiertos cerca de usted en este momento.",
  "Take it": "Tomarlo",
  "Rewards": "Recompensas",
  "Couldn't take it": "No se pudo tomar",
  "Priority": "Prioridad",
  "This customer asked for you.": "Este cliente lo pidió a usted.",
  "The job goes back out right away. Inside 24 hours of the arrival window it counts as a late cancel.": "El trabajo se vuelve a ofrecer de inmediato. Dentro de las 24 horas antes del horario de llegada cuenta como cancelación tardía.",
  "Standby requests": "Solicitudes de respaldo",
  "Another pro has these jobs. If they can't make it, you get the first call. Passing is free; you're paid only if you're called and do the job.": "Otro profesional tiene estos trabajos. Si no puede ir, usted recibe la primera llamada. Pasar es gratis; solo se le paga si lo llamamos y hace el trabajo.",
  "Backup": "Respaldo",
  "Yes, I can cover": "Sí, puedo cubrir",
  "You're on standby": "Está de respaldo",
  "Can't anymore": "Ya no puedo",
  "24h+ out: free · 6–24h: short notice, no penalty · under 6h: late cancel. Never a charge to your pay.": "Con 24 h+: gratis · 6–24 h: poca anticipación, sin penalidad · menos de 6 h: cancelación tardía. Nunca hay cargo a su pago.",
  "Your cancellations": "Sus cancelaciones",
  "days": "días",
  "late": "tardías",
  "no-shows": "inasistencias",
  "short notice": "con poca anticipación",
  "free": "gratis",
  "excused": "excusadas",
  "Only late cancels (3) and no-shows (2) in 90 days lead to a written warning. Hand jobs back early so your backup can take them.": "Solo las cancelaciones tardías (3) y las inasistencias (2) en 90 días llevan a una advertencia por escrito. Devuelva los trabajos con tiempo para que su respaldo los tome.",
};
