/*
 * FILE    : apps/mobile/lib/es-pro.ts
 * PROJECT : Handled (myhumanai) — AI-run home & business services
 * CREATED : 2026-10-02_1405 UTC
 * UPDATED : 2026-10-02_1405 UTC — English / Spanish.
 * PURPOSE : Spanish for the pro screens of the app (offers, jobs, calendar, earnings).
 */
export const ES_PRO: Record<string, string> = {
  // Time windows
  "Morning (8–11am)": "Mañana (8–11 a. m.)",
  "Midday (11am–2pm)": "Mediodía (11 a. m.–2 p. m.)",
  "Afternoon (2–5pm)": "Tarde (2–5 p. m.)",
  "Any time that day": "Cualquier hora ese día",

  // Common
  "Couldn't update": "No se pudo actualizar",
  "Try again": "Inténtelo de nuevo",
  "Cancel": "Cancelar",
  "Loading…": "Cargando…",
  "Never mind": "No importa",
  "Yes": "Sí",
  "No": "No",

  // Pro home
  "Setup & documents": "Configuración y documentos",
  "Earnings": "Ganancias",
  "You're on call": "Está de guardia",
  "Off call": "Fuera de guardia",
  "Same-day jobs near you come to you first": "Los trabajos para el mismo día cerca de usted le llegan primero",
  "until": "hasta las",
  "Go on call to get same-day jobs, even on a day you don't usually work.": "Póngase de guardia para recibir trabajos para el mismo día, incluso en un día que normalmente no trabaja.",
  "Go off call": "Salir de guardia",
  "On call": "De guardia",
  "Sharing your location while on call or on a job today (app open only).": "Compartiendo su ubicación mientras está de guardia o en un trabajo hoy (solo con la app abierta).",
  "Your location isn't shared when you're off call and not on a job.": "Su ubicación no se comparte cuando está fuera de guardia y no está en un trabajo.",
  "My calendar & days off": "Mi calendario y días libres",
  "New offers": "Nuevas ofertas",
  "No open offers. We'll notify you when one comes in.": "No hay ofertas abiertas. Le avisaremos cuando llegue una.",
  "site visit": "visita al sitio",
  "View & accept": "Ver y aceptar",
  "My schedule": "Mi agenda",
  "Nothing scheduled.": "Nada programado.",

  // Earnings
  "Payout setup": "Configuración de pagos",
  "Not available yet": "Aún no disponible",
  "Cash out now?": "¿Cobrar ahora?",
  "Cash out": "Cobrar",
  "Couldn't cash out": "No se pudo cobrar",
  "Ready to pay out": "Listo para pagar",
  "Instant pay": "Pago inmediato",
  "Approved payouts go out free on the weekly run.": "Los pagos aprobados se envían gratis en el pago semanal.",
  "connect your bank or debit card through Stripe once, then cash out any time for": "conecte su banco o tarjeta de débito mediante Stripe una vez y luego cobre cuando quiera por",
  "Set up instant pay": "Configurar pago inmediato",
  "Paid to you this year:": "Pagado a usted este año:",
  "Payouts": "Pagos",
  "No payouts yet this year.": "Aún no hay pagos este año.",
  "instant": "inmediato",
  "fee": "cargo",
  "Full statement & 1099 (web)": "Estado de cuenta completo y 1099 (web)",
  // Payout kinds
  "Job": "Trabajo",
  "Show-up pay": "Pago por presentarse",
  "Weekly minimum": "Mínimo semanal",
  "Insurance stipend": "Subsidio de seguro",
  "Materials": "Materiales",
  "Adjustment": "Ajuste",
  // Payout statuses
  "pending": "pendiente",
  "approved": "aprobado",
  "paid": "pagado",
  "held": "retenido",
  "clawback": "reembolso",
  // Instant pay / reimbursement reasons
  "not offered right now": "no se ofrece en este momento",
  "pro isn't active": "el profesional no está activo",
  "not offered for this trade": "no se ofrece para este oficio",
  "pro not found": "profesional no encontrado",

  // Job sheet
  "Upload failed": "Error al subir",
  "Receipt": "Recibo",
  "Add the amount, what you bought and a photo of the receipt.": "Agregue el monto, lo que compró y una foto del recibo.",
  "Not accepted": "No aceptado",
  "Receipt sent": "Recibo enviado",
  "Sent for approval.": "Enviado para aprobación.",
  "Approved — you're reimbursed once the customer pays.": "Aprobado: se le reembolsa cuando el cliente pague.",
  "Not sent": "No enviado",
  "Change order sent": "Orden de cambio enviada",
  "Can't get in": "No puede entrar",
  "Say what happened (knocked, called, gate locked…).": "Indique qué pasó (tocó, llamó, portón cerrado…).",
  "Couldn't send": "No se pudo enviar",
  "We're on it": "Nos encargamos",
  "We're calling the customer now. Please wait 15 minutes on site. A confirmed lockout earns show-up pay.": "Estamos llamando al cliente ahora. Espere 15 minutos en el lugar. Un acceso denegado confirmado recibe pago por presentarse.",
  "Payout": "Pago",
  "On my way": "En camino",
  "The customer can see your ETA while the app is open.": "El cliente puede ver su hora estimada de llegada mientras la app está abierta.",
  "I've arrived — start job": "Ya llegué: iniciar trabajo",
  "Finish the job": "Terminar el trabajo",
  "Photograph every area you worked on. AI checks them and approves your payout.": "Fotografíe cada área en la que trabajó. La IA las revisa y aprueba su pago.",
  "Take photos": "Tomar fotos",
  "Note for the customer (optional)": "Nota para el cliente (opcional)",
  "Mark complete": "Marcar como terminado",
  "Submitted — AI quality check in progress.": "Enviado: revisión de calidad con IA en curso.",
  "More work than booked?": "¿Más trabajo del reservado?",
  "Update the scope to what's really here": "Actualice el alcance a lo que realmente hay",
  "The difference is priced at our standard rates and sent to the customer to approve and pay.": "La diferencia se cotiza con nuestras tarifas estándar y se envía al cliente para que la apruebe y pague.",
  "What you found (the customer sees this)": "Lo que encontró (el cliente lo verá)",
  "Extra for the customer:": "Cargo adicional para el cliente:",
  "No extra charge for this change": "Sin cargo adicional por este cambio",
  "Send change order": "Enviar orden de cambio",
  "Can't get in?": "¿No puede entrar?",
  "Can't get access": "No puede acceder",
  "Knocked and called at 9:05, gate locked, no answer…": "Toqué y llamé a las 9:05, portón cerrado, nadie respondió…",
  "Report no access": "Reportar falta de acceso",
  "Purchases": "Compras",
  "Reimbursement:": "Reembolso:",
  "Materials for this job are included in your payout.": "Los materiales de este trabajo están incluidos en su pago.",
  "Store purchases for the customer": "Compras en tienda para el cliente",
  "Parts not included in the price": "Piezas no incluidas en el precio",
  "$ amount": "Monto en $",
  "What you bought (e.g. groceries at Kroger)": "Lo que compró (p. ej., víveres en Kroger)",
  "What you bought (e.g. wax ring + supply line)": "Lo que compró (p. ej., anillo de cera + manguera de suministro)",
  "Receipt added ✓ (retake)": "Recibo agregado ✓ (volver a tomar)",
  "Photo of receipt": "Foto del recibo",
  "Submit receipt": "Enviar recibo",
  // Expense statuses
  "waiting for approval": "en espera de aprobación",
  "approved — waiting on the customer": "aprobado: en espera del cliente",
  "reimbursed": "reembolsado",
  "not approved": "no aprobado",

  // Calendar
  "My calendar": "Mi calendario",
  "Change usual days, hours or daily limit": "Cambiar días habituales, horario o límite diario",
  "Today": "Hoy",
  "booked": "reservados",
  "Day off": "Día libre",
  "Doesn't work Sundays": "No trabaja los domingos",
  "Doesn't work Mondays": "No trabaja los lunes",
  "Doesn't work Tuesdays": "No trabaja los martes",
  "Doesn't work Wednesdays": "No trabaja los miércoles",
  "Doesn't work Thursdays": "No trabaja los jueves",
  "Doesn't work Fridays": "No trabaja los viernes",
  "Doesn't work Saturdays": "No trabaja los sábados",
  "Reopen this day": "Reabrir este día",
  "Take this day off": "Tomar este día libre",

  // Offer
  "Offer unavailable": "Oferta no disponible",
  "Loading offer…": "Cargando oferta…",
  "Not available": "No disponible",
  "Another pro may have taken it.": "Es posible que otro profesional la haya tomado.",
  "It's yours": "Es suyo",
  "The full address and customer details are now unlocked.": "La dirección completa y los datos del cliente ya están desbloqueados.",
  "Where": "Dónde",
  "Scope": "Alcance",
  "Start time": "Hora de inicio",
  "Included:": "Incluye:",
  "Customer:": "Cliente:",
  "Instructions:": "Instrucciones:",
  "Job terms": "Condiciones del trabajo",
  "Your payout": "Su pago",
  "Site visit": "Visita al sitio",
  "Expires in": "Vence en",
  "I agree to this work order and its job terms": "Acepto esta orden de trabajo y sus condiciones",
  "Pass": "Pasar",
  "Accept job": "Aceptar trabajo",
  "You accepted this job": "Usted aceptó este trabajo",
  "This offer expired or another pro took it.": "Esta oferta venció u otro profesional la tomó.",
  // Fixed job terms from the work order
  "Arrive within the booked window. Running late? Message the customer in the app before the window starts.": "Llegue dentro del horario reservado. ¿Va con retraso? Envíe un mensaje al cliente en la app antes de que empiece el horario.",
  "Take before-and-after photos of every area you work on and upload them to complete the job.": "Tome fotos de antes y después de cada área en la que trabaje y súbalas para terminar el trabajo.",
  "The customer has paid a deposit; we collect the balance before your start date. Don't start until the app shows \"Paid in full\".": "El cliente pagó un depósito; cobramos el saldo antes de su fecha de inicio. No comience hasta que la app muestre \"Pagado en su totalidad\".",
  "Out-of-scope work: stop and tell us — we send the customer a change order. Do only what's on this work order.": "Trabajo fuera del alcance: deténgase y avísenos; le enviamos al cliente una orden de cambio. Haga solo lo que está en esta orden de trabajo.",
  "Parts not included in the price: upload the receipt in the app. Small amounts are approved automatically; call us before a big purchase. You're reimbursed at cost once the customer pays.": "Piezas no incluidas en el precio: suba el recibo en la app. Los montos pequeños se aprueban automáticamente; llámenos antes de una compra grande. Se le reembolsa al costo cuando el cliente pague.",
  "Can't get in? Tap “Can't get in?” in the app and wait 15 minutes while we call the customer. A confirmed lockout earns show-up pay.": "¿No puede entrar? Toque “¿No puede entrar?” en la app y espere 15 minutos mientras llamamos al cliente. Un acceso denegado confirmado recibe pago por presentarse.",
  "Don't solicit this customer to book directly with you for 12 months.": "No le pida a este cliente que reserve directamente con usted durante 12 meses.",
  "Licensed trade: your license must be valid for this work; pull permits where required.": "Oficio con licencia: su licencia debe ser válida para este trabajo; obtenga los permisos donde se requieran.",
  "Event work: be set up and ready before the start time; coordinate with the on-site planner.": "Trabajo de eventos: esté instalado y listo antes de la hora de inicio; coordine con el organizador en el lugar.",
};
