/*
 * FILE    : scripts/build-interview-packet.ts
 * PROJECT : Handled (myhumanai) — AI-run home & business services
 * CREATED : 2026-10-05_0246 UTC
 * PURPOSE : Writes docs/INTERVIEW_PACKET_<timestamp>.md from packages/core/src/interview.ts (the same source as
 *           the Hub packet page and the AI interviewer). Run: node --experimental-strip-types scripts/build-interview-packet.ts
 */
import { writeFileSync } from "node:fs";
import { COMPETENCIES, DO_NOT_ASK, INTERVIEW_FAQ, INTERVIEW_PASS, QUESTIONS, type Competency } from "../packages/core/src/interview.ts";

const ts = new Date().toISOString().slice(0, 16).replace("T", "_").replace(":", "");
const file = `docs/INTERVIEW_PACKET_${ts}.md`;
const groups = [...new Set(QUESTIONS.filter((q) => q.group).map((q) => q.group!))];
const qline = (q: (typeof QUESTIONS)[number], n: number) => `${n}. **${q.en}**  \n   _ES: ${q.es}_  \n   ✔ Look for: ${q.lookFor}${q.redFlag ? `  \n   ✖ Red flag: ${q.redFlag}` : ""}  \n   Scores: ${q.competency ? COMPETENCIES[q.competency].en : "not scored"}`;
const md = `<!--
  FILE    : ${file}
  PROJECT : Handled (myhumanai) — AI-run home & business services
  CREATED : ${ts} UTC (generated by scripts/build-interview-packet.ts — edit packages/core/src/interview.ts, then re-run)
  PURPOSE : The pro screening interview packet: process, what not to ask, questions, scoring guide, approval checklist.
-->

# Pro interview packet

Screening interview for independent pros (1099 businesses). The same questions and scoring are used by the AI
interviewer, the Hub scorecard and the printable page (Hub → Recruiting → Interview packet). **A person makes every
decision.** Say "approved to receive job offers", not "hired".

## 1. How a pro gets approved
1. Applies at /pros. An AI screens their business qualifications.
2. **Screening interview:** either the AI interviewer (a private link by email, about 15 minutes, English or Spanish) or a person, in person or by phone.
3. **A person decides:** invite, follow up, or decline.
4. **Setup in the pro portal:**
   - W-9
   - independent contractor agreement
   - specialties
   - work area and days
   - insurance certificate (general liability, plus trade coverages)
   - workers' comp or a no-employees statement
   - trade license where required
   - photo ID check
   - background check
   - payout method
5. We verify the documents and the background check clears. They're then **approved to receive job offers**.
6. **First jobs are probation:** smaller jobs, a human review of each one, and a call to the customer.

## 2. Never ask about
${DO_NOT_ASK.map((d) => `- ${d.en} / _${d.es}_`).join("\n")}

If a candidate brings one of these up, don't follow up and don't let it affect the decision. Score what they said,
not their accent, grammar or which language they use. Say yes to accommodation requests, such as more time, a phone
interview or an interpreter.

## 3. Questions for everyone
${QUESTIONS.filter((q) => !q.group).map((q, i) => qline(q, i + 1)).join("\n")}

## 4. Questions by trade
${groups.map((g) => `### ${g}\n${QUESTIONS.filter((q) => q.group === g).map((q, i) => qline(q, i + 1)).join("\n")}`).join("\n\n")}

## 5. Scoring guide (1–5)
| Competency | 1 — concerning | 3 — meets | 5 — excellent |
|---|---|---|---|
${(Object.keys(COMPETENCIES) as Competency[]).map((c) => `| ${COMPETENCIES[c].en} | ${COMPETENCIES[c].anchors[1]} | ${COMPETENCIES[c].anchors[3]} | ${COMPETENCIES[c].anchors[5]} |`).join("\n")}

**How the result is worked out:**
- **Advance:** the average of the six scores is ${INTERVIEW_PASS.average} or more, and no score is below ${INTERVIEW_PASS.floor}.
- **Follow up:** any score is very low, or a competency wasn't covered.
- **Not now:** the average is under 2.6, or there's a knockout.

**Knockouts:**
- won't carry required insurance
- would do licensed work without the license
- would knowingly continue unsafe work
- abusive or threatening in the interview

## 6. What the AI interviewer may tell candidates
${INTERVIEW_FAQ.map((f) => `- ${f}`).join("\n")}

**How the AI interviewer is set up:**
- It says it's an AI before starting, and the candidate agrees before it begins.
- The candidate can ask for a person instead at any point.
- A person reviews every interview and makes the decision.
- Scores come with quoted evidence, and the result is computed from the rubric above.

## 7. Approval checklist
${["Application received", "Application screened", "Screening interview done", "Decision by a person: invite", "W-9 on file", "Independent contractor agreement signed", "Specialties chosen", "Work area & days set", "Insurance certificate (COI) verified", "Trade coverages verified (where the trade needs them)", "Workers' comp, or a no-employees statement", "Trade license verified (where required)", "Photo ID verified", "Background check cleared", "Payout method set", "Approved — receiving job offers", "First job completed and reviewed"].map((x) => `- [ ] ${x}`).join("\n")}

The Hub tracks every step for each candidate (Hub → Recruiting → click a name). It shows the next step and who it
waits on, and flags anyone stuck: 2+ days waiting on a decision from us, or 7+ days with no progress.
`;
writeFileSync(file, md);
console.log(`wrote ${file}`);
