/*
 * FILE    : scripts/gen-seed.ts
 * PROJECT : Handled — AI-run home & business services
 * CREATED : 2026-10-01_1723 UTC
 * PURPOSE : Generates supabase/seed.sql from the @handled/core catalog so the database
 *           service list never drifts from the pricing engine. Also seeds a launch
 *           market and demo pros/jobs for the ops hub.
 *           Writes TWO files:
 *             supabase/seed.sql       — production: service catalog + launch market only
 *             supabase/demo_data.sql  — optional demo pros/jobs for a staging project. NEVER
 *                                       run it on the live database.
 *           Run: node --experimental-strip-types scripts/gen-seed.ts
 */

import { SERVICES, defaultAnswers, estimate } from "../packages/core/src/index.ts";

const q = (v: unknown) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a: string[]) => `array[${a.map(q).join(",")}]::text[]`;
const stamp = new Date().toISOString().slice(0, 16).replace("T", "_").replace(":", "");

import { writeFileSync } from "node:fs";

const out: string[] = [];
out.push(`-- ============================================================================
-- FILE    : supabase/seed.sql   (generated by scripts/gen-seed.ts — do not hand edit)
-- PROJECT : Handled — AI-run home & business services
-- CREATED : ${stamp} UTC
-- PURPOSE : PRODUCTION seed — service catalog + launch market. Safe to re-run.
-- ============================================================================
`);

out.push("insert into public.services (slug, name, category, minimum, payout_share, site_visit, sort) values");
out.push(
  SERVICES.map((s, i) => `  (${q(s.slug)}, ${q(s.name)}, ${q(s.category)}, ${s.minimum}, ${s.payoutShare}, ${s.siteVisit}, ${i})`).join(",\n") +
    "\non conflict (slug) do update set name = excluded.name, category = excluded.category, minimum = excluded.minimum,\n  payout_share = excluded.payout_share, site_visit = excluded.site_visit, sort = excluded.sort;\n",
);

out.push(`insert into public.markets (name, state, zip_prefixes)
select 'Metro Detroit', 'MI', array['480','481','482','483'] where not exists (select 1 from public.markets where name = 'Metro Detroit');\n`);
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n") + "\n");

out.length = 0;
out.push(`-- ============================================================================
-- FILE    : supabase/demo_data.sql   (generated by scripts/gen-seed.ts — do not hand edit)
-- PROJECT : Handled — AI-run home & business services
-- CREATED : ${stamp} UTC
-- PURPOSE : DEMO pros, jobs, applications and a B2B lead for a STAGING project.
--           ⚠ NEVER run on the live database — these are fake people and fake jobs.
-- ============================================================================
`);

const pros = [
  ["Sparkle Squad Cleaning", "Dana Reyes", "dana@sparklesquad.example", ["cleaning", "windows", "carpet"], 4.9, 212, 4],
  ["GreenLine Lawn & Tree", "Marcus Bell", "marcus@greenline.example", ["lawn", "tree", "gutters"], 4.8, 156, 5],
  ["Haul Pros Detroit", "Tony Brooks", "tony@haulpros.example", ["hauling"], 4.7, 98, 4],
  ["Fix-It Fred", "Fred Okafor", "fred@fixitfred.example", ["handyman"], 4.95, 340, 3],
  ["Scoop Troop", "Lena Park", "lena@scooptroop.example", ["pet_waste", "lawn"], 4.85, 410, 12],
  ["Midwest Remodel Co.", "Sam Patel", "sam@midwestremodel.example", ["remodel", "handyman"], 4.8, 64, 1],
] as const;
out.push("insert into public.contractors (business_name, contact_name, email, phone, trades, service_zips, status, rating, jobs_completed, acceptance_rate, on_time_rate, insured_until, background_checked, daily_capacity, coverage, license_number) values");
out.push(
  pros
    .map(
      ([biz, name, email, trades, rating, jobs, cap], i) =>
        `  (${q(biz)}, ${q(name)}, ${q(email)}, '(313) 555-01${String(10 + i)}', ${arr([...trades])}, ${arr(["48201", "48202", "48226", "482*"])}, 'approved', ${rating}, ${jobs}, ${(0.8 + i * 0.03).toFixed(2)}, ${(0.9 + i * 0.015).toFixed(3)}, current_date + 200, true, ${cap}, '{"auto":"2099-12-31","bond":"2099-12-31","workers_comp":"2099-12-31"}', ${trades.some((t: string) => ["remodel", "plumbing", "electrical", "hvac"].includes(t)) ? q(`MI-DEMO-${100 + i}`) : "null"})`,
    )
    .join(",\n") + "\non conflict (email) do nothing;\n",
);

const demo = [
  ["house-cleaning", "Alicia Grant", "48201", "requested", "biweekly"],
  ["junk-removal", "Brightside Dental", "48226", "scheduled", "once"],
  ["tree-removal", "Kevin Moore", "48202", "site_visit", "once"],
  ["pet-waste-removal", "Priya Shah", "48201", "assigned", "weekly"],
  ["bathroom-remodel", "Jordan Lee", "48202", "quoted", "once"],
  ["gutter-cleaning", "Hector Diaz", "48226", "completed", "once"],
] as const;
out.push("insert into public.jobs (service_slug, contact_name, contact_email, contact_phone, customer_type, company_name, address, city, state, zip, answers, frequency, scheduled_date, time_window, estimate_low, estimate_high, status, source) values");
out.push(
  demo
    .map(([slug, name, zip, status, freq], i) => {
      const svc = SERVICES.find((s) => s.slug === slug)!;
      const answers = defaultAnswers(svc);
      const e = estimate({ slug, answers, frequency: freq });
      const biz = name.includes("Dental");
      return `  (${q(slug)}, ${q(name)}, ${q(name.toLowerCase().replace(/\W+/g, ".") + "@example.com")}, '(313) 555-02${10 + i}', '${biz ? "commercial" : "residential"}', ${biz ? q(name) : "null"}, '${100 + i * 37} Woodward Ave', 'Detroit', 'MI', ${q(zip)}, ${q(JSON.stringify(answers))}::jsonb, '${freq}', current_date + ${i + 1}, 'morning', ${e.low}, ${e.high}, '${status}', 'web')`;
    })
    .join(",\n") + ";\n",
);
out.push(`-- assign the demo 'assigned' + 'completed' jobs to a matching pro
update public.jobs j set contractor_id = c.id, contractor_payout = floor(j.estimate_low * s.payout_share)
from public.contractors c, public.services s
where s.slug = j.service_slug and j.status in ('assigned','completed') and j.service_slug = 'pet-waste-removal' and c.email = 'lena@scooptroop.example';
update public.jobs j set contractor_id = c.id, contractor_payout = floor(j.estimate_low * s.payout_share), price_final = j.estimate_low, completed_at = now()
from public.contractors c, public.services s
where s.slug = j.service_slug and j.status = 'completed' and c.email = 'marcus@greenline.example';
`);

out.push(`-- every non-site-visit job has a firm price; every job past booking has been paid (upfront)
update public.jobs set price_final = estimate_low where price_final is null and status not in ('site_visit','quoted');
update public.jobs set price_final = coalesce(price_final, estimate_low), paid_at = now(), amount_paid = coalesce(price_final, estimate_low)
where status in ('scheduled','dispatched','assigned','in_progress','qa_review','completed');
update public.jobs j set contractor_payout = floor(j.price_final * s.payout_share) from public.services s
where s.slug = j.service_slug and j.paid_at is not null and j.contractor_payout is null;
`);
out.push(`insert into public.contractor_applications (business_name, contact_name, email, phone, trades, zips, years_experience, crew_size, insured, message) values
  ('Clear View Windows', 'Ray Thompson', 'ray@clearview.example', '(313) 555-0301', array['windows','gutters'], '48201, 48202', 6, 2, true, 'Two-man crew, own lifts, 6 years in business.');
`);
out.push(`insert into public.business_accounts (company, contact_name, email, locations, services_needed, status, monthly_value) values
  ('Brightside Dental', 'Office Manager', 'office@brightside.example', 3, array['house-cleaning','window-cleaning'], 'proposal', 2400);
`);

writeFileSync(new URL("../supabase/demo_data.sql", import.meta.url), out.join("\n") + "\n");
console.log("wrote supabase/seed.sql and supabase/demo_data.sql");
